### ISSUE TITLE
User Name is cut when non-alphanumeric char encountered

### ISSUE THREAD

**Issue by oleg-bronzhaiev** [rojter-tech/pluradl.py#11]
When "-" or "." char encountered in User Name, the program cuts it right after that char (I didn't test other non-alphanumeric chars).

E.g. if the following args provided:
`python pluradl.py --user "pluralsight-user" --pass "XXX"`
Pluradl will cut User Name to "pluralsight" :(

P.S. I've discovered that by debugging.

**Comment by rojter-tech** [comment]
should  now be fixed in latest release
