### ISSUE TITLE
Change the language of the subtitles

### ISSUE THREAD

**Issue by joelrojas** [rojter-tech/pluradl.py#15]
Hi, sorry for this noob question, But how can I change the subtitles from **en** to **es**.

**Comment by rojter-tech** [comment]
> Hi, sorry for this noob question, But how can I change the subtitles from **en** to **es**.

Pluralsight does'nt support other languages than english. Youtube-dl and Plura-dl is just a implementation of extracting data from external sources.

**Comment by SebasAas** [comment]
@joelrojas una buena opcion seria descargar los subtitulos aunque esten en ingles y posteriormente entrar en una pagina de traductor de archivos .srt, de dejo una que estoy usando yo
https://subtitlestranslator.com/
