### ISSUE TITLE
Donwload Only subtitles

### ISSUE THREAD

**Issue by gleitoncampos** [rojter-tech/pluradl.py#17]
Hi!!

First of all, thanks a lot for this. It's working like a cham for me!

I just want to know if is possible to skip the videos e ONLY donwload the captions (srt files).

**Comment by valdemirfilho** [comment]
Hi, in addition, download all subtitles is not working.

**Comment by rojter-tech** [comment]
> Hi!!
> 
> First of all, thanks a lot for this. It's working like a cham for me!
> 
> I just want to know if is possible to skip the videos e ONLY donwload the captions (srt files).

@GleitonCampos It might be a way of doing that safely, the main problem is that the download request pattern needs to be sparse and unpredictable seen from the serverside of this implementation, thus you wont be able to download subtitles fast. Therefore I think it is not worth it.

**Comment by gleitoncampos** [comment]
Hmm.. Unterdstood. Thanks tor the attention anyway. Keep the good work on this project!
