### ISSUE TITLE
Accept Arguments/Flags in the pluraexercise Script

### ISSUE THREAD

**Issue by prikhi** [rojter-tech/pluradl.py#18]
Hey, it'd be super nice if I could automate exercise fetching by passing in my username & password to the `pluraexercise.py` script like we can with `pluradl.py`.

Thanks for the great package!

**Comment by rojter-tech** [comment]
@prikhi Yes, it should not cause too much headache because the implementation is already integrated in pluradl.py :). I could accualy have a look right away. I will close this when I push the changes to master.

**Comment by rojter-tech** [comment]
@prikhi Done :P

**Comment by prikhi** [comment]
Awesome, thanks for the quick turnaround!
