### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [rojter-tech/pluradl.py#2]
Hey there.

If the course have a number in the link id you get this error:
courses/.log
```
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: option --playlist-end: invalid integer value: 'ableton-live-9-introduction'
```

**Comment by 7wOv6ySCjo** [comment]
Hey @rojter-tech Can you help me please?

**Comment by rojter-tech** [comment]
@7wOv6ySCjo I will have a look, thank you.

**Comment by rojter-tech** [comment]
It should be fixed by now

**Comment by 7wOv6ySCjo** [comment]
How to use ScrapeUtils?

**Comment by rojter-tech** [comment]
> How to use ScrapeUtils?

For loading ALL courses an easy way is to visit [the search enginge](https://www.pluralsight.com/search?categories=course&sort=title) sorting by title. Then keep hitting **LOAD MORE** at the bottom of the page. If you and your computer ram are quick enough it should take less than 5 minutes.

Then save the resulting [html as a file](https://github.com/rojter-tech/pluradl.py/blob/master/scrapeutils/data/search_results.html). Now scrape the file by using [00_scrape_html_to_json.py](https://github.com/rojter-tech/pluradl.py/blob/master/scrapeutils/00_scrape_html_to_json.py)

This procedure will save the resulting list as [data/courses.json](https://github.com/rojter-tech/pluradl.py/blob/master/scrapeutils/data/courses.json). Finally you could filter this result with [01_json_to_txt.py](https://github.com/rojter-tech/pluradl.py/blob/master/scrapeutils/01_json_to_txt.py) to produce a filtered text output, for example [big-data.txt](https://github.com/rojter-tech/pluradl.py/blob/master/scrapeutils/filtered_results/big-data.txt).

You could imaging doing the same procedure for another subset of courses, for example filtering by JAVA or Data Science courses first and then save the the resulting page html.
