### ISSUE TITLE
Can't continue from where it left off

### ISSUE THREAD

**Issue by mertselimb** [rojter-tech/pluradl.py#20]
Hi, thanks for the cool app. When i download a course with lets say 70 videos and stop after 50. Progress resets. Inprogress directory transfered to failed so when i start it again it starts with the first video. If i just copy them to inprogress. It shows error then deletes them.

**Comment by rojter-tech** [comment]
> Hi, thanks for the cool app. When i download a course with lets say 70 videos and stop after 50. Progress resets. Inprogress directory transfered to failed so when i start it again it starts with the first video. If i just copy them to inprogress. It shows error then deletes them.

You have to manually specify which videos you would like to download (instructions in readme). It does not keep track of or detect which state you are/were in.
