### ISSUE TITLE
folder structure option

### ISSUE THREAD

**Issue by ehsansajjad-synergy** [rojter-tech/pluradl.py#22]
how we can provide the folder structure same as on pluralsight like we do in youtube-dl ?

**Comment by rojter-tech** [comment]
> how we can provide the folder structure same as on pluralsight like we do in youtube-dl ?

@ehsansajjad-synergy 

If you are talking about the output template it is controlled by row 23.

```python
23 FILENAME_TEMPLATE = r"%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s"
```

**Comment by ehsansajjad-synergy** [comment]
@rojter-tech  will it generate it by default ?
 because it is putting all videos in single folder

**Comment by rojter-tech** [comment]
> @rojter-tech will it generate it by default ?
> because it is putting all videos in single folder

@ehsansajjad-synergy What do you mean with generated by default? It is hard coded into the pluradl.py script. The syntax for the output template is exactly the same as youtube-dl:

[https://github.com/ytdl-org/youtube-dl#output-template](https://github.com/ytdl-org/youtube-dl#output-template)

**Comment by ehsansajjad-synergy** [comment]
@rojter-tech I meant was how i can specify the template in the shell when executing ?

**Comment by rojter-tech** [comment]
> @rojter-tech I meant was how i can specify the template in the shell when executing ?

What you can do is specfified in the [README.md](https://github.com/rojter-tech/pluradl.py/blob/master/README.md) file.

**Comment by ehsansajjad-synergy** [comment]
Thanks @rojter-tech  it helped
