### ISSUE TITLE
way to simulate I am watching the video

### ISSUE THREAD

**Issue by CarlosJoseChaconChavarria** [rojter-tech/pluradl.py#23]
hi

is there a way to simulate  I am watching the video? I really don't care to just download like 3 courses  per day but simulate I am watching the video at  2.x for example.... maybe setting the download limit to 1MB or something like that not sure
thanks

**Comment by CarlosJoseChaconChavarria** [comment]
BTW I think it does not matter to simulate what I asking I just check how it works it just downloads the whole video file at the beginning 

so not sure now

**Comment by rojter-tech** [comment]
@karlochacon Your question really depends on what you mean with "simulate 2.x watch speed". In one hand, because the download rate limit (by default) is 1000 kb/s and because the bitrate of the video content (by average) is ~300 kb/s the average "speed watch" is 3,33333.x.

Is this what you are asking?

**Comment by CarlosJoseChaconChavarria** [comment]
basically I downloaded a software which limits my download speed for python process to 100Kbs so videos take some more time to download plus the the average 90 to 120 seconds for the next video to download maybe I can simulate I am watching the video at 2.x their maximum watching speed

If a video is about 8 minutes so download time plus your added sleep time takes about 4 minutes to go from one video to another to try to simulate that 

I was seeing the video with my speed connection took about 15 seconds to get downloaded in normal conditions

I am not sure is this is going to help me in any way....the thing is PS marks your courses as seen once you download a course and who in earth is going to believe that I  just watched a 4 hours videos in 1 hour  and 30 minutes

**Comment by rojter-tech** [comment]
There is however a "built in" limiter in pluradl.py:

```python
11  # IMPORTANT SETTINGS TO PREVENT SPAM BLOCKING OF YOUR ACCOUNT/IP AT  PLURALSIGHT # # # # # # # # # #
12  SLEEP_INTERVAL = 60     # minimum sleep time                   #                                  #
13  SLEEP_OFFSET   = 120    # adding random sleep time up to       #  Change this at your own risk.   #
14  SLEEP_PLAYLIST = 60     # sleep time between playlist requests #                                  #
15  RATE_LIMIT     = 10**6  # download rate in bytes/s             #                                  #
16  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
```

which is responsible for the "default 3.3333.x watch speed", which is a quite reasonable upper limit in my opinion. If someone are tweaking other aspects of the rate limit then ofc the speed can only be lower than this. This hopefully clear out any questions about this issue. Closing this,
