### ISSUE TITLE
Doubt about download

### ISSUE THREAD

**Issue by SebasAas** [rojter-tech/pluradl.py#31]
Hey there, I have a doubt about the downloads, i did a personal courselist with a lot of course that i want, two days ago I started the script and now when I want to make a modification to the courselist file I no longer see it in the root folder, so my question is, if I cancel the script will I recover the file or will it be stored in another folder?

**Comment by rojter-tech** [comment]
> Hey there, I have a doubt about the downloads, i did a personal courselist with a lot of course that i want, two days ago I started the script and now when I want to make a modification to the courselist file I no longer see it in the root folder, so my question is, if I cancel the script will I recover the file or will it be stored in another folder?

@SebasAas The courselist.txt file is neved modified. It has even to be specified manually independently, otherwise the program terminates. Straight speaking, it is hard-coded to be opened by the script.

```bash
(base) [dreuter@rOjterArchSurface pluradl.py]$ mkdir tmp
(base) [dreuter@rOjterArchSurface pluradl.py]$ mv courselist.txt tmp/
(base) [dreuter@rOjterArchSurface pluradl.py]$ python pluradl.py 
Enter you Pluralsight credentials
Enter username: mybeautifulverygoodandshortpluralsightusername
Enter password (will not be displayed)
: 
Setting username to: mybeautifulverygoodandshortpluralsightusername
Downloading subtitles is set to: on 

There is no courselist.txt in script path. Terminating script ...
(base) [dreuter@rOjterArchSurface pluradl.py]$ 

```
