### ISSUE TITLE
Scrapping is being detected: Needs more wait times

### ISSUE THREAD

**Issue by nekag67502** [rojter-tech/pluradl.py#33]
Accounts are getting banned just from the initial scrapping.
I just downloaded ONE video and got banned
Ideally there should be a (configurable) wait time before every single HTTP request.

**Comment by rojter-tech** [comment]
@nekag67502 In what context did this issue occur? Can you share the log file?

**Comment by rojter-tech** [comment]
no response, issue untrackable
