### ISSUE TITLE
Exercise Files: Download Button not clickable

### ISSUE THREAD

**Issue by Taranis01** [rojter-tech/pluradl.py#34]
The download of the exercise files stops regularly because the button is sometimes covered.
Added error message and [screenshot](https://i.ibb.co/c29CQ5M/error.png)
Manually removing the cookie-dialog helps, so maybe pluraexercise.py could remove first?

>DevTools listening on ws://127.0.0.1:50836/devtools/browser/456bf189-2d2b-4b1c-bffc-6e74da27ed5e
Traceback (most recent call last):
  File "pluraexercise.py", line 146, in <module>
    main()
  File "pluraexercise.py", line 139, in main
    download_routine(driver, course[0], sleep_time=5)
  File "pluraexercise.py", line 61, in download_routine
    wait_for_access(driver, DOWNLOAD_EXERCISE_FILE, timer=sleep_time).click()
  File "C:\Users\Test\Anaconda3\envs\Test1\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Test\Anaconda3\envs\Test1\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Test\Anaconda3\envs\Test1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Test\Anaconda3\envs\Test1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button data-css-w1d8qf="">...</button> is not clickable at point (128, 757). Other element would receive the click: <div data-css-1mo2ruv="">...</div>
  (Session info: chrome=80.0.3987.163)

**Comment by D34d3nd** [comment]
Same issue as me using latest clone from GIT. I was getting by it by just clicking the download button myself on the page it was stuck on. Then start back up pluralexercise.py and it would see it already downloaded.

**Comment by rojter-tech** [comment]
@Taranis01 Yes, this is the downside of this feature. Remote control of graphical targets is a pure RPA solution, and in case of Selenium the button have to be exposed visually. I have tried to find ways to injecting JavaScript, but unfortunately PluralSight has worked hard to ensure real mouse clicks for that particular button. 

Selenium documentation can be [found here](https://selenium-python.readthedocs.io/).

**Comment by prikhi** [comment]
Is it because of the cookies pop up?

Maybe try adding a call to `set_window_size` to bump up the window height:
https://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.set_window_size
