### ISSUE TITLE
SOMEONE WANNA HELP!?

### ISSUE THREAD

**Issue by hewfuiohweuiohfuioew** [rojter-tech/pluradl.py#37]
Downloading subtitles is set to: on 

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] plura-dl version 1.0.0b4
[debug] Git HEAD: 618d80d
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] networking-cisco-ccna-200-125-100-105: Downloading JSON metadata
[pluralsight:course] networking-cisco-ccna-200-125-100-105: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Github/pluradl.py/plura_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/unrecognized/Github/pluradl.py/plura_dl/PluraDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

Something went wrong.
The download request for 'networking-cisco-ccna-200-125-100-105' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/networking-cisco-ccna-200-125-100-105
exists or that your subscription is valid for accessing its content.

Moving content to /home/unrecognized/Github/pluradl.py/courses/_failed/networking-cisco-ccna-200-125-100-105
Moving to next course playlist

Sleeping for 80 seconds ...

WHAT AM I DOING WRONG?

**Comment by hewfuiohweuiohfuioew** [comment]
I am not bann i cant execute i did everything good I install python3.8.2 , paste the id of the course , execute and error all time

**Comment by Taranis01** [comment]
I have just resolved the same error:
* new account
* new python environment
* US VPN
* cookies and custom user agent ( `python pluradl.py -u "username" -p "password" --cookies "path_to_cookie.txt" --user-agent "custom_user_agent"` )

However i can't tell you what did the trick. It is either the python environment, the US VPN or the cookies or a combination of these.

**Comment by rojter-tech** [comment]
referring to [#12](https://github.com/rojter-tech/pluradl.py/issues/12)
