### ISSUE TITLE
403 Error - after downloading first video : Unable to download JSON metadata:

### ISSUE THREAD

**Issue by betterversion** [rojter-tech/pluradl.py#38]
```python
[pluralsight:course] csharp-fundamentals-dev: Downloading JSON metadata
[download] Downloading playlist: C# Fundamentals
[pluralsight:course] playlist C# Fundamentals: Collected 96 video ids (downloading 96 of them)
[download] Downloading video 1 of 96
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Downloading JSON metadata
[pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Waiting for 4 seconds to avoid throttling
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1586805660/7d714fa12709a3b42af856bf35bf3a7e/clips/resolution/83e472fe-1c5a-45ef-bce0-7120bea00dea/current/mp4/1280x720.mp4'
[download] Sleeping 174.38 seconds...
[download] Destination: 01-1-Course_Overview-1280x720.mp4

[K[download]   0.0% of 2.71MiB at 886.93KiB/s ETA 00:03

[K[download]   0.1% of 2.71MiB at 746.98KiB/s ETA 00:03

[K[download]   0.3% of 2.71MiB at 839.53KiB/s ETA 00:03

[K[download]   0.5% of 2.71MiB at 618.52KiB/s ETA 00:04

[K[download]   1.1% of 2.71MiB at 958.95KiB/s ETA 00:02

[K[download]   2.3% of 2.71MiB at 667.39KiB/s ETA 00:04

[K[download]   4.6% of 2.71MiB at 972.33KiB/s ETA 00:02

[K[download]   9.2% of 2.71MiB at 966.91KiB/s ETA 00:02

[K[download]  18.4% of 2.71MiB at 973.56KiB/s ETA 00:02

[K[download]  36.9% of 2.71MiB at 971.19KiB/s ETA 00:01

[K[download]  71.8% of 2.71MiB at 971.96KiB/s ETA 00:00

[K[download] 100.0% of 2.71MiB at 973.22KiB/s ETA 00:00

[K[download] 100% of 2.71MiB in 00:03
[download] Downloading video 2 of 96
[pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Downloading JSON metadata
[pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Downloading mp4-high-widescreen viewclip JSON
Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Waiting for 4 seconds to avoid throttling
[0;31mERROR:[0m No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/foobar/Documents/pluradl.py/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/foobar/Documents/pluradl.py/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/foobar/Documents/pluradl.py/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/home/foobar/Documents/pluradl.py/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Something went wrong.
The download request for 'csharp-fundamentals-dev' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/csharp-fundamentals-dev
exists or that your subscription is valid for accessing its content.

Moving content to /home/foobar/Documents/pluradl.py/courses/_failed/csharp-fundamentals-dev

```

**Comment by hewfuiohweuiohfuioew** [comment]
could u help me @betterversion ?

**Comment by betterversion** [comment]
@hewfuiohweuiohfuioew  need more details ?

**Comment by rojter-tech** [comment]
> ```python
> [pluralsight:course] csharp-fundamentals-dev: Downloading JSON metadata
> [download] Downloading playlist: C# Fundamentals
> [pluralsight:course] playlist C# Fundamentals: Collected 96 video ids (downloading 96 of them)
> [download] Downloading video 1 of 96
> [pluralsight] Downloading login page
> [pluralsight] Logging in
> [pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Downloading JSON metadata
> [pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Downloading mp4-high-widescreen viewclip graphql
> [pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Downloading mp4-high-widescreen viewclip JSON
> [pluralsight] e5b410b9-67dc-4e4a-9d15-291ea436fa3d-0: Waiting for 4 seconds to avoid throttling
> [debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1586805660/7d714fa12709a3b42af856bf35bf3a7e/clips/resolution/83e472fe-1c5a-45ef-bce0-7120bea00dea/current/mp4/1280x720.mp4'
> [download] Sleeping 174.38 seconds...
> [download] Destination: 01-1-Course_Overview-1280x720.mp4
> 
> �[K[download]   0.0% of 2.71MiB at 886.93KiB/s ETA 00:03
> 
> �[K[download]   0.1% of 2.71MiB at 746.98KiB/s ETA 00:03
> 
> �[K[download]   0.3% of 2.71MiB at 839.53KiB/s ETA 00:03
> 
> �[K[download]   0.5% of 2.71MiB at 618.52KiB/s ETA 00:04
> 
> �[K[download]   1.1% of 2.71MiB at 958.95KiB/s ETA 00:02
> 
> �[K[download]   2.3% of 2.71MiB at 667.39KiB/s ETA 00:04
> 
> �[K[download]   4.6% of 2.71MiB at 972.33KiB/s ETA 00:02
> 
> �[K[download]   9.2% of 2.71MiB at 966.91KiB/s ETA 00:02
> 
> �[K[download]  18.4% of 2.71MiB at 973.56KiB/s ETA 00:02
> 
> �[K[download]  36.9% of 2.71MiB at 971.19KiB/s ETA 00:01
> 
> �[K[download]  71.8% of 2.71MiB at 971.96KiB/s ETA 00:00
> 
> �[K[download] 100.0% of 2.71MiB at 973.22KiB/s ETA 00:00
> 
> �[K[download] 100% of 2.71MiB in 00:03
> [download] Downloading video 2 of 96
> [pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Downloading JSON metadata
> [pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Downloading mp4-high-widescreen viewclip graphql
> [pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Downloading mp4-high-widescreen viewclip JSON
> Unable to download JSON metadata: HTTP Error 403: Forbidden
> [pluralsight] 38d7675f-942c-4673-a6af-bc44f7a3d8eb-0: Waiting for 4 seconds to avoid throttling
> �[0;31mERROR:�[0m No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/home/foobar/Documents/pluradl.py/plura_dl/PluraDL.py", line 797, in extract_info
>     ie_result = ie.extract(url)
>   File "/home/foobar/Documents/pluradl.py/plura_dl/extractor/common.py", line 530, in extract
>     ie_result = self._real_extract(url)
>   File "/home/foobar/Documents/pluradl.py/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
>     self._sort_formats(formats)
>   File "/home/foobar/Documents/pluradl.py/plura_dl/extractor/common.py", line 1327, in _sort_formats
>     raise ExtractorError('No video formats found')
> plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
> 
> Something went wrong.
> The download request for 'csharp-fundamentals-dev' was forced to terminate.
> Double check that https://app.pluralsight.com/library/courses/csharp-fundamentals-dev
> exists or that your subscription is valid for accessing its content.
> 
> Moving content to /home/foobar/Documents/pluradl.py/courses/_failed/csharp-fundamentals-dev
> ```

Some courses allows the first video being downloaded even though the subscription is not covering that course. Please check the course url if you have access.

**Comment by betterversion** [comment]
@rojter-tech thanks for getting back, that makes sense as usually 1st video is available for public view. from start, I tried to download that course a couple of days ago and the internet disconnected after finishing 50/96.
I actually did checked : 1) the course was available and the course page opens ; 2) and subscription was valid as I didn't get 403 on login. However I didn't check if videos were loading succesfully. 
Is it possible to check if the course is available for download based on a subscription before making an attempt to download a course? Or maybe just add these details when rethrowing exception: ```Some courses allow the first video being downloaded even though the subscription is not covering that course. Please check the course URL if you have access.```

**Comment by rojter-tech** [comment]
> @rojter-tech thanks for getting back, that makes sense as usually 1st video is available for public view. from start, I tried to download that course a couple of days ago and the internet disconnected after finishing 50/96.
> Is it possible to check if the course is available for download based on a subscription before making an attempt to download a course? Or maybe just add these details when rethrowing exception: `Some courses allow the first video being downloaded even though the subscription is not covering that course. Please check the course URL if you have access.`

It may be, I have not looked into it :). I am scraping [public information about the courses](https://github.com/rojter-tech/pluradl.py/blob/master/data/courses.json) and collecting all the course relevant information that is availble. None of those pieces of information is subscription details.

>     "getting-started-aspdotnet-mvcservice-stack-bootstrap": {
>         "author": "Jesse Liberty",
>         "date": "Nov 29 2013",
>         "length": 156,
>         "level": "Intermediate",
>         "rating": 405,
>         "title": "Getting Started with ASP.NET MVC, ServiceStack and Bootstrap",
>         "url": "https://www.pluralsight.com/courses/getting-started-aspdotnet-mvcservice-stack-bootstrap"
>     },

**Comment by fortunewalla** [comment]
My experiences:
------------------
If a course is not downloaded properly or error during download.

1) Move the course folder/directory from 'failed' to 'inprogress' and try again after 1 hour.
2) If access error again - Account maybe be blocked.

The tool works perfectly. The website security is very sensitive to usage.

* Don't use the script and website at the same time.
* Don't use many instances of the script. Only one script run at a time.
* Keep a gap of at least 30-45min between each course download. 
* Spread your usage throughout the day.
* Better to complete a course on website and then after 1 hour use the script to download. This shows up as you are reviewing the course again.

All the best!

**Comment by betterversion** [comment]
The cause why I have been blocked is that max allowed time that trial user can watch is 200 minutes. Didn't know that it was counting toward my watched minutes. Maybe it would be good to add some logs to track of how many minutes (content) was already downloaded
