### ISSUE TITLE
Issue when selecting courses

### ISSUE THREAD

**Issue by Bigemul** [rojter-tech/pluradl.py#41]
Hi

There is a small problem when I select courses. If I select intervals for courses, the next ones need to have intervals. Otherwise, the program will consider that they don't need to be downloaded.

I had:
N°1 (start) (end)
N°2 (start) (end)
N°3
N°4
N°5

Fom N°3 to N°5, courses were ignored.

```
[pluralsight:course] malware-analysis-big-picture: Downloading JSON metadata
[download] Downloading playlist: Malware Analysis: The Big Picture
[pluralsight:course] playlist Malware Analysis: The Big Picture: Collected 56 video ids (downloading 0 of them)
[download] Finished downloading playlist: Malware Analysis: The Big Picture
The course 'malware-analysis-big-picture' was downloaded successfully.
Moving content to /Users/my_name/Downloads/pluradl.py-master y/courses/_finished/malware-analysis-big-picture
```

**Comment by Bigemul** [comment]
I must precise what happened. Yesterday, I saw the interval being applied to the next courses.

**Comment by reqser** [comment]
i had this too, first intervalled setting applied the others, it needs to redownload all lists
