### ISSUE TITLE
Sleeping Time not accurate

### ISSUE THREAD

**Issue by erikbwu** [rojter-tech/pluradl.py#47]
First, I wanted to say a huge Thank You for making this possible for all this people who don't know how to scrape the videos!  So after downloading like 13 Videos sucessfully  the sleep timer is incorrect or the program doesn't continue. Do you know what the problem could be? It already fetched the metadata.
![Screenshot (4)_LI](https://user-images.githubusercontent.com/57805895/79453080-711c2980-7fe9-11ea-9ca6-56b7ca9a32bc.jpg)

**Comment by Taranis01** [comment]
I had the same, similar as explained [here](https://superuser.com/questions/312132/command-prompt-hangs-until-keypress). Could you try to activate the windows and press enter? If that helps, then dont do any funny Key or Mouse actions, while the windows is still active, in the future ;-)

**Comment by erikbwu** [comment]
Thanks, I won't ;) Yes after restarting or activating the window it runs again smoothly
