### ISSUE TITLE
Anyway to get the course list of recently added?

### ISSUE THREAD

**Issue by austinbarberrepo** [rojter-tech/pluradl.py#61]
Is there any way to get the course list of only the recently added ones instead of going through the github history to see what has been added. Would be nice to see what new courses come out and if I'd like to grab them or not. 

Thanks!

**Comment by rojter-tech** [comment]
@abarber229 Yes, in [data/courses.json](https://github.com/rojter-tech/pluradl.py/blob/master/data/courses.json) the date information is provided. It is an easy task so sort by that parameter.
