### ISSUE TITLE
Download course lessons sametime as videos?

### ISSUE THREAD

**Issue by doublemint12** [rojter-tech/pluradl.py#62]
Hello,

First of all, thank you so much for doing thing.
I was quickly wondering if it's okay to download course lessons at the same time running in a separate terminal. 

Please advise me if this is a bad approach, but I was just going to run all the courses in the main courselist.txt file and erase them later. My understanding is that that it's better to have video downloads completed because it will automatically put the correct course lessons into their respective course folders?
 
And lastly, is it okay to download the whole course-list or will I run into some trouble later on? It looks like the clone is just right for not to go over the throttle limit and raise issues??

Thank you!

**Comment by Bigemul** [comment]
You shouldn't watch videos and download them at the same time with the same account. You have to enter your username in pluradl and on Pluralsight. They will detect two connections at the same time. It's like having your cake and eating it at the same time. You can't having it both ways.

There are more than 8K lines in course-list. You shouldn't use it. Your account would end up banned except if you only download 1 or 2 per day. The free month will come to an end and you'd have "useless" courses on your computer. You should focus courses that you really want.

**Comment by doublemint12** [comment]
Thank you very much. So what is the point of pluradl if you have access and can downloaded courses as well?

**Comment by Bigemul** [comment]
> So what is the point of pluradl if you have access and can downloaded courses as well?
What was your question ?
I'll answer to the part I understood : the whole point of pluradl is to give you permanent access to your videos.

**Comment by Bigemul** [comment]
> So what is the point of pluradl if you have access and can downloaded courses as well?

What was your question?
I'll answer to the part I understood : the whole point of pluradl is to give you permanent access to your videos.

**Comment by doublemint12** [comment]
Sorry, I'm a noob. So it seems like I will no longer have the access to my downloaded courses that I got using their Pluralsight software. Is this why Pluraldl exists?

**Comment by Bigemul** [comment]
The only goal of those download softwares consists in giving you permanent access to videos so that you don't need subscription when you have enough content to learn from.
