### ISSUE TITLE
No video formats found.

### ISSUE THREAD

**Issue by bkwoka** [rojter-tech/pluradl.py#64]
No video formats found. All time this message

**Comment by Bigemul** [comment]
Could you post the entire log file?

**Comment by ann-bereza** [comment]
[pluralsight:course] emotional-intelligence-introduction: Downloading JSON metadata
[download] Downloading playlist: Introduction to Emotional Intelligence
[pluralsight:course] playlist Introduction to Emotional Intelligence: Collected 39 video ids (downloading 39 of them)
[download] Downloading video 1 of 39
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] emotional-intelligence-introduction-m1-0: Downloading JSON metadata
[pluralsight] emotional-intelligence-introduction-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] emotional-intelligence-introduction-m1-0: Downloading mp4-high-widescreen viewclip JSON
Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] emotional-intelligence-introduction-m1-0: Waiting for 4 seconds to avoid throttling
[0;31mERROR:[0m No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/annhavelia/Documents/pluralsight/pluradl.py/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/annhavelia/Documents/pluralsight/pluradl.py/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/annhavelia/Documents/pluralsight/pluradl.py/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/Users/annhavelia/Documents/pluralsight/pluradl.py/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Something went wrong.
The download request for 'emotional-intelligence-introduction' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/emotional-intelligence-introduction
exists or that your subscription is valid for accessing its content.

Moving content to /Users/annhavelia/Documents/pluralsight/pluradl.py/courses/_failed/emotional-intelligence-introduction

**Comment by ann-bereza** [comment]
here's the log file with the same error from me

**Comment by bkwoka** [comment]
[download] Downloading video 1 of 11
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] 6dd98b90-8681-475d-8f18-2ac016ffcfdd-0: Downloading JSON metadata
[pluralsight] 6dd98b90-8681-475d-8f18-2ac016ffcfdd-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 6dd98b90-8681-475d-8f18-2ac016ffcfdd-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 6dd98b90-8681-475d-8f18-2ac016ffcfdd-0: Waiting for 5 seconds to avoid throttling
[pluralsight] 6dd98b90-8681-475d-8f18-2ac016ffcfdd-0: Downloading captions JSON
[info] Writing video subtitles to: 01-1-Course_Overview-1280x720.en.srt
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1588967210/3b1fe37b7790cfbb4884b6f6f8d9aff9/clips/resolution/d02cea55-d41f-4e24-9a26-813758bf8463/current/mp4/1280x720.mp4'
[download] Sleeping 61.01 seconds...
[download] Destination: 01-1-Course_Overview-1280x720.mp4
[download]   0.0% of 8.47MiB at Unknown speed ETA Unknown ETA
[download]   0.0% of 8.47MiB at Unknown speed ETA Unknown ETA
[download]   0.1% of 8.47MiB at Unknown speed ETA Unknown ETA
[download]   0.2% of 8.47MiB at Unknown speed ETA Unknown ETA
[download]   0.4% of 8.47MiB at Unknown speed ETA Unknown ETA
[download]   0.7% of 8.47MiB at  3.98MiB/s ETA 00:02
[download]   1.5% of 8.47MiB at 1016.14KiB/s ETA 00:08
[download]   2.9% of 8.47MiB at  1.33MiB/s ETA 00:06
[download]   5.9% of 8.47MiB at  1.39MiB/s ETA 00:05
[download]  11.8% of 8.47MiB at  1.42MiB/s ETA 00:05
[download]  23.6% of 8.47MiB at  1.41MiB/s ETA 00:04
[download]  40.0% of 8.47MiB at  1.42MiB/s ETA 00:03
[download]  57.0% of 8.47MiB at  1.42MiB/s ETA 00:02
[download]  74.0% of 8.47MiB at  1.42MiB/s ETA 00:01
[download]  90.7% of 8.47MiB at  1.42MiB/s ETA 00:00
[download] 100.0% of 8.47MiB at  1.43MiB/s ETA 00:00
[download] 100% of 8.47MiB in 00:06
[download] Downloading video 2 of 11
[pluralsight] play-by-play-google-cloud-platform-windows-dotnet-m1-0: Downloading JSON metadata
[pluralsight] play-by-play-google-cloud-platform-windows-dotnet-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] play-by-play-google-cloud-platform-windows-dotnet-m1-0: Downloading mp4-high-widescreen viewclip JSON
Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] play-by-play-google-cloud-platform-windows-dotnet-m1-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\upc-PC\Desktop\projets\pluradl.py-master\plura_dl\PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\upc-PC\Desktop\projets\pluradl.py-master\plura_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\upc-PC\Desktop\projets\pluradl.py-master\plura_dl\extractor\pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "C:\Users\upc-PC\Desktop\projets\pluradl.py-master\plura_dl\extractor\common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Something went wrong.
The download request for 'play-by-play-google-cloud-platform-windows-dotnet' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/play-by-play-google-cloud-platform-windows-dotnet
exists or that your subscription is valid for accessing its content.

Moving content to C:\Users\upc-PC\Desktop\projets\pluradl.py-master\courses\_failed\play-by-play-google-cloud-platform-windows-dotnet
Moving to next course playlist

**Comment by bkwoka** [comment]
403: Forbidden - you have no access to this course
