### ISSUE TITLE
It's not possible to download more than 200 minutes

### ISSUE THREAD

**Issue by ann-bereza** [rojter-tech/pluradl.py#67]
I have found out that for trial accounts Pluralsight allows only 200 minutes to watch, and after downloading one course I have noticed that I am already run out of that limit, though I have only registered yesterday. I am not able to download any more courses right now. If anyone found a workaround for that - pls, let me know.

**Comment by CarlosJoseChaconChavarria** [comment]
there is no workaround...... trial limit is 200min
